import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalNavbar } from "@/components/Navbar";
import { AuthProvider } from "@/context/SessionContext";
import { Toaster } from "sonner";
import Footer from "@/components/Footer";
import "@copilotkit/react-ui/styles.css";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import { CopilotKit } from "@copilotkit/react-core";
import { CopilotPopup } from "@copilotkit/react-ui";
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Groills | Skills Swaping",
  description: "Generated By Vivek Singh",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-1000 text-foreground`}
      >
        <AuthProvider>
          <GlobalNavbar />
          <CopilotKit publicApiKey={process.env.NEXT_COPILOT_PUBLIC_KEY}>
            {children}
            <CopilotPopup
              instructions={
                "You are assisting the user as best as you can. Answer in the best way possible given the data you have."
              }
              labels={{
                title: "Groills Ai Assistant",
                initial: "Need any help?",
              }}
            />
          </CopilotKit>
          <Toaster />
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
